apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: web
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: test-proj
  source:
    #path: argocd/manifests/kafka
    repoURL: https://github.com/ad-it/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true